### ISSUE TITLE
Infer Depencdencies Using the Variable's Function

### ISSUE THREAD

**Issue by seyhani** [seyhani/causality#34]
Before:
```
m.add('C', lambda vals: vals['A'] and vals['B'], ['A', 'B'])
```
After:
```
m.add('C', lambda vals: vals['A'] and vals['B'])
```

**Comment by mahykari** [comment]
A new object will be added, which provides the following method:

```python
find(f: Callable[[VALS], bool]) -> Set[str]
```

This method returns all keys from an instance of _VALS_ which are accessed by _f_.

Issue #40 adds this functionality.
